STEMS = {}

STEMS["All"] = {
'-aa-' : 'USAN not to use',
'-abine' : 'see -arabine/-citabine',
'-ac' : 'anti-inflammatory agents acetic acid derivatives',
'-acetam' : 'see -racetam',
'-acid-' : 'derivatives',
'-actide' : 'synthetic corticotropins',
'-adol-' : 'analgesics mixed opiate receptor agonists/antagonists',
'-adom' : 'analgesics, tifluadom derivatives',
'-adox' : 'antibacterials quinoline dioxide derivatives',
'-ae-' : 'USAN not to use',
'-afenone' : 'antiarrhythmics propafenone derivatives',
'-afil' : 'pde5 inhibitors',
'-ai-' : 'USAN not to use',
'-aj-' : 'antiarrhythmics ajmaline derivatives',
'-al' : 'aldehydes',
'-aldol-' : 'analgesics mixed opiate receptor agonists/ antagonists',
'-aldrate' : 'antacid aluminum salts',
'-algron' : 'alpha1 - and alpha2 - adrenoreceptor agonists',
'-alol' : 'combined alpha and beta blockers',
'-alox' : 'antacids, aluminium derivatives',
'-amidine' : 'pentamidine derivatives/analogues',
'-amidis' : 'antimyloidotics',
'-amivir' : 'see -vir',
'-amostat' : 'proteolytic enzyme inhibitors',
'-ampa-' : 'ionotropic non-nmda n-methyl d-aspartate glutamate receptors',
'-ampanel' : 'antagonists',
'-ampator' : 'modulators',
'-andr-' : 'androgens',
'-anib' : 'angiogenesis inhibitors',
'-anide' : 'saluretics',
'-anserin' : 'serotonin 5-ht2 receptor antagonists',
'-antel' : 'anthelmintics undefined group',
'-antrone' : 'antineoplastics; anthraquinone derivatives',
'-ao-' : 'USAN not to use',
'-apine' : 'tricyclic compounds',
'-apsel' : 'p-selectin antagonists',
'-ar-' : 'USAN not to use; reserved for stereochemical compounds',
'-arabine' : 'antineoplastics arabinofuranosyl derivatives fludarabine',
'-aril-' : 'antiviral arildone derivatives',
'-arit' : 'antirheumatics lobenzarit type',
'-arol' : 'anticoagulants dicumarol type',
'-arone' : 'antiarrhythmics',
'-arot-' : 'arotinoids',
'-arotene' : 'arotinoid derivatives',
'-arsin' : 'organoarsenic compounds',
'-ase' : 'enzymes',
'-ast' : 'antiasthmatics/antiallergics not acting primarily as antihistamines; leukotriene biosynthesis inhibitors',
'-asteride' : 'androgens / anabolic steroids',
'-astine' : 'antihistaminics histamine-h1 receptor antagonists',
'-asvir' : 'see -vir',
'-atadine' : 'tricyclic antiasthmatics',
'-ate' : 'cellulose derivatives',
'-au-' : 'USAN not to use',
'-axine' : 'antianxiety, antidepressant inhibitor of norepinephrine and dopamine re-uptake',
'-axo-' : 'rat-murine hybrid antibodies',
'-axomab' : 'see mab',
'-azam' : 'diazepam derivatives',
'-azenil' : 'benzodiazepine receptor agonists/antagonists',
'-azepam' : 'antianxiety agents diazepam type',
'-azepide' : 'cholecystokinin receptor antagonists',
'-azocine' : 'narcotic antagonists/agonists 6,7-benzomorphan derivatives',
'-azolam' : 'diazepam derivatives',
'-azoline' : 'antihistamines/local vasoconstrictors antazoline type',
'-azone' : 'anti-inflammatory analgesics, phenylbutazone derivatives',
'-azosin' : 'antihypertensives prazosin type',
'-bacept' : 'b-cells',
'-bactam' : 'beta-lactamase inhibitors',
'-bamate' : 'tranquilizers/antiepileptics propanediol and pentanediol groups',
'-barb-' : 'barbituric acid derivatives',
'-basib' : 'inhibitors of the adam a disintegrin and a metalloprotease enzymes sheddases',
'-begron' : 'beta 3 adrenoreceptor agonist',
'-ben-' : 'USAN not to use; chemical connotations',
'-benakin' : 'interleukin-1 -b analogues and derivatives',
'-bendan' : 'cardiac stimulants, pimobendan derivatives',
'-bendazole' : 'anthelmintics tibendazole type',
'-bercept' : 'review -cept',
'-berel' : 'beta estrogen receptor agonist',
'-bermin' : 'vascular endothelial growth factors',
'-bersat' : 'anticonvulsants; antimigraine benzoylamino-benzpyran derivatives',
'-betasol' : 'prednisone and prednisolone derivatives',
'-betin' : 'amyloid b ab binders',
'-bol-' : 'anabolic steroids',
'-bove' : 'bovine somatotropin derivatives',
'-bradine' : 'bradycardic agents',
'-brate' : 'clofibrate derivatives',
'-brutinib' : 'see -tinib',
'-bu-' : 'USAN not to use; chemical connotations',
'-bufen' : 'non-steroidal anti-inflammatory agents, fenbufen derivatives',
'-bulin' : 'antineoplastics mitotic inhibitors; tubulin binders',
'-butan' : 'antiseptics dapabutan type',
'-butazone' : 'anti-inflammatory analgesics phenylbutazone type',
'-buvir' : 'rna polymerase ns5b inhibitor',
'-buzone' : 'anti-inflammatory analgesics, phenylbutazone derivatives',
'-caftor' : 'cystic fibrosis transmembrane regulator cftr protein modulators',
'-cain-' : 'class i antiarrhythmics, procainamide and lidocaine derivatives',
'-caine' : 'local anesthetics',
'-calaret' : 'calcium receptor antagonists',
'-calcet' : 'calcium receptor agonists',
'-calci-' : 'vitamin d analogues',
'-caleret' : 'calcium receptor antagonists',
'-camra' : 'antivirals intracellular adhesion molecules, icam-1 derivatives',
'-camsule' : 'camphorsulfonic acid derivatives used as uva sunscreens',
'-capoc' : 'agonists of the gardos channel, or the calcium activated potassium channel of intermediate conductance',
'-capone' : 'catechol-o-methyltransferase comt inhibitors',
'-carbef' : 'antibiotics carbacephem derivatives',
'-carnil' : 'benzodiazepine receptor antagonists/agonists carboline derivatives',
'-casan' : 'caspase interleukin 1b converting enzyme inhibitors',
'-caserin' : 'serotonin receptor agonists, primarily 5-ht2',
'-castat' : 'see -stat',
'-cat-' : 'USAN not to use; chemical connotations',
'-catib' : 'cathespin inhibitors',
'-cavir' : 'see -vir',
'-cel-' : 'USAN not to use; chemical connotations',
'-cellose' : 'cellulose ether derivatives',
'-cept' : 'receptor molecules, native or modified  a preceding infix should designate the target',
'-cerfont' : 'crf-1 corticotropin releasing factor receptor antagonists',
'-cet' : 'receptors small molecule',
'-cetrapib' : 'cholesterol ester transfer protein inhibitors',
'-ch-' : 'USAN not to use',
'-cic' : 'hepatoprotectives timonacic type',
'-ciclib' : 'cyclin dependent kinase inhibitors formerly -cidib',
'-ciclovir' : 'see vir-',
'-cidib' : 'cyclin dependent kinase inhibitor',
'-cidin' : 'natural antibiotics undefined group',
'-ciguat' : 'guanaline cyclase activator',
'-cillide' : 'antibiotics, 6-aminopenicillanic acid derivatives',
'-cillin' : 'penicillins',
'-cillinam' : 'antibiotics, 6-aminopenicillanic acid derivatives',
'-cilpine' : 'tricyclic compounds',
'-cirnon' : 'cc chemokine receptor 9 ccr9 antagonists',
'-cisteine' : 'mucolytics, other than bromhexine derivatives',
'-citabine' : 'nucleoside antiviral or antineoplastic agents, cytarabine or azarabine derivatives',
'-citinib' : 'see -tinib',
'-cizumab' : 'see -mab',
'-clidine' : 'muscarinic agonists various indications',
'-clidinium' : 'muscarinic receptor agonists/antagonists see also -ium',
'-clomol' : 'heat-shock protein inducers, bimoclomal type',
'-clone' : 'hypnotics/tranquilizers zopclone type',
'-closporin' : 'immunosuppressants cyclosporine type',
'-clostox' : 'botulinum toxins',
'-co-' : 'complement receptors',
'-cocept' : 'see -cept',
'-codar' : 'see dar',
'-cog' : 'blood coagulation factors',
'-cogin' : 'blood coagulation cascade inhibitor',
'-conazole' : 'systemic antifungals miconazole type',
'-corat' : 'glucocorticoid receptor agonists  not glucocorticoids',
'-cort-' : 'cortisone derivatives',
'-coxib' : 'cyclooxygenase-2 inhibitors',
'-cri-' : 'acridinecarboxamide derivatives',
'-cridar' : 'see -dar',
'-crinat' : 'diuretics ethacrynic acid derivatives',
'-crine' : 'acridine derivatives',
'-criviroc' : 'ccr5 antagonists, immunomodulators',
'-cromil' : 'antiallergics cromoglicic acid derivatives',
'-curium' : 'neuromuscular blocking agents quaternary',
'-curonium' : 'neuromuscular blocking agents quaternary ammonium compounds',
'-cycline' : 'antibiotics tetracycline derivatives',
'-cyclovir' : 'antivirals acyclovir type',
'-dan' : 'positive inotropic agents pimobendan type',
'-dapsone' : 'antimycobacterials diaminodiphenylsulfone derivatives',
'-dar' : 'multidrug resistance inhibitors',
'-dd-' : 'USAN not to use',
'-decakin' : 'interleukin-10 analogues and derivatives',
'-degib' : 'hedgehog signaling inhibitors',
'-denant' : 'adenosine 2a antagonists',
'-denoson' : 'adenosine a receptor agonists',
'-depsin' : 'depsipeptide derivatives',
'-dermin' : 'see -ermin',
'-dex-' : 'USAN not to use; reserved for stereochemical compounds',
'-dil-' : 'vasodilators undefined group',
'-dilol' : 'vasodilators',
'-dipine' : 'phenylpyridine vasodilators nifedipine type',
'-dismase' : 'superoxide dismutase activity',
'-distim' : 'conjugates of two different types of colony-stimulating factors',
'-ditan' : 'antimigraine 5-ht1 receptor agonists',
'-ditraz' : 'acaricide/tick repellent',
'-dodekin' : 'interleukin-12 analogues and derivatives',
'-domide' : 'thalidomide derivatives',
'-dopa' : 'dopamine receptor agonists',
'-dopidine' : 'dopamine d2 receptor modulator',
'-dore' : 'dopamine d2d3 receptor modulators',
'-dotin' : 'synthetic analogs of the dolastatin series',
'-dotril' : 'see -tril/trilat',
'-dox' : 'antibacterials, quinazoline dioxide derivatives',
'-dralazine' : 'antihypertensives hydrazine-phthalazines',
'-drimer' : 'see -mer',
'-drine' : 'sympathomimetics',
'-dronate' : 'calcium metabolism regulators',
'-dronic' : 'calcium metabolism regulator, pharmaceutical aid',
'-dutant' : 'see -tant',
'-dyl' : 'vasodilators',
'-ea-' : 'USAN not to use',
'-ectedin' : 'ecteinascodin derivatives',
'-ectin' : 'antiparasitics ivermectin type',
'-ee-' : 'USAN not to use',
'-ei-' : 'USAN not to use',
'-elestat' : 'elastase inhibitors',
'-elvakin' : 'see -kin',
'-elvekin' : 'interleukin-11 analogues and derivatives',
'-emcinal' : 'erythromycin derivatives lacking antibiotic activity',
'-enicokin' : 'interleukin-21',
'-entan' : 'endothelin receptor antagonists',
'-eo-' : 'USAN not to use',
'-epag' : 'reduce conflicts with stems beginning with ne-, harmonize with inn experts, better reflect action at ep2 receptor',
'-eptacog' : 'blood coagulation factor vii',
'-eptakin' : 'see -kin',
'-erg-' : 'ergot alkaloid derivatives',
'-eridine' : 'analgesics meperidine type',
'-ermin' : 'growth factors',
'-espib' : 'heat shock protein inhibitors',
'-estr-' : 'estrogens',
'-estrant' : 'estrogen antagonists',
'-etanide' : 'diuretics piretanide type',
'-ethidine' : 'analgesics, pethidine derivatives',
'-eu-' : 'USAN not to use',
'-exakin' : 'see -kin',
'-exine' : 'mucolytic, bromhexine derivatives',
'-ezolid' : 'oxazolidinone antibacterials',
'-facept' : 'lymphocyte function-associated with antigen 3 lfa receptor',
'-farcept' : 'interferon receptors',
'-farin' : 'warfarin analogs',
'-farnib' : 'farnesyl transferase inhibitor',
'-faxine' : 'antianxiety, antidepressant inhibitor of norepinephrine and dopamine re-uptake',
'-fen-' : 'USAN not to use; chemical connotations',
'-fenacin' : 'muscarinic receptor antagonists',
'-fenamate' : 'fenamic acid ester or salt derivatives',
'-fenamic' : 'anti-inflammatory agents anthranilic acid',
'-fenin' : 'diagnostic aids phenylcarbamoylmethyl iminodiacetic acid derivatives',
'-fenine' : 'analgesics fenamic acid subgroup',
'-fensine' : 'norepinephrine, serotonin, dopamine, reuptake inhibitor',
'-fentanil' : 'narcotic analgesics fentanyl derivatives',
'-fentrine' : 'phosphodiesterase inhibitor',
'-fermin' : 'see -ermin',
'-fetamin' : 'amfetamine derivatives',
'-fetamine' : 'amfetamine derivatives',
'-fexor-' : 'farnesoid x receptor agonists',
'-fexorate' : 'farnesoid x receptor agonists',
'-fiba-' : 'platelet aggregation inhibitor gpiib/iiia receptor',
'-fiban' : 'receptor antagonists glycoprotein iib/iiia receptor antagonists',
'-fibatide' : 'see -tide',
'-fibrate' : 'antihyperlipidemics clofibrate type',
'-fibric acid' : 'antihyperlipidemics clofibrate type',
'-filcon' : 'hydrophilic contact lens materials',
'-filermin' : 'leukemia-inhibiting factor',
'-fingol' : 'sphingosine derivatives',
'-flapon' : '5-lipoxygenase-activating protein flap inhibitors',
'-flu-' : 'USAN not to use; chemical connotations',
'-flurane' : 'general inhalation anesthetics halogenated alkane derivatives',
'-fo-' : 'USAN not to use; chemical connotations',
'-focon' : 'hydrophobic contact lens materials',
'-folastat' : 'see -stat',
'-formin' : 'hypoglycemics phenformin type',
'-fos-' : 'USAN not to use; chemical connotations',
'-fosfamide' : 'isophosphoramide mustard derivatives',
'-fovir' : 'phosphonic acid derivatives',
'-fradil' : 'calcium channel blockers acting as vasodilators',
'-frine' : 'sympathomimetic, phenethyl derivatives',
'-fulven' : 'antineoplastic, acylfulven derivatives',
'-fungin' : 'antifungal antibiotics undefined group',
'-fylline' : 'theophylline derivatives',
'-gab-' : 'gabamimetics',
'-gacestat' : 'gamma secretase inhibitors',
'-ganan' : 'antimicrobial, bactericidal permeability increasing polypeptide',
'-gapil' : 'neuronal apoptosis inhibitors; gapdh',
'-gaptide' : 'gap junction protein channel modulators',
'-gatran' : 'thrombin inhibitors argatroban type',
'-gene' : 'gene therapy products',
'-gepant' : 'calcitonin gene-related peptide receptor antagonists',
'-gest-' : 'progestins',
'-gestr-' : 'estrogens',
'-giline' : 'mao inhibitors, type b',
'-gillin' : 'antibiotics aspergillus strains',
'-gli-' : 'antihyperglycemics',
'-gliatin' : 'glucokinase enzyme inhibitors typically antidiabetics',
'-gliflozin' : 'phlorozin derivatives, phenolic glycosides',
'-glinide' : 'antidiabetic, sglt2 inhibitors, not phlorozin derivatives',
'-gliptin' : 'dipeptidyl aminopeptidase-iv inhibitors',
'-glitazar' : 'ppar agonists not thiazolidene derivatives',
'-glitazone' : 'ppst agonists thiazolidene derivatives',
'-glumide' : 'cck antagonists, antiulcer, anxiolytic agent',
'-glurant' : 'metabotropic glutamate receptor antagonists, negative allosteric modulators',
'-glustat' : 'glucosyltransferase inhibitors',
'-glutide' : 'glp peptide analogs',
'-golide' : 'dopamine receptor agonists, ergoline derivatives',
'-golix' : 'gnrh receptor antagonists nonpeptide',
'-gosivir' : 'see -vir',
'-gramostim' : 'granulocyte macrophage colony- stimulating factors gm-csf',
'-grastim' : 'see -stim',
'-grel-' : 'platelet aggregation inhibitors',
'-h-' : 'USAN not to use',
'-ia-' : 'USAN not to use',
'-ibat' : 'ileal bile acid transport inhibitor',
'-ibine' : 'ribofuranyl-derivatives of the "pyrazofurin" type',
'-icam' : 'anti-inflammatory agents isoxicam type',
'-icodar' : 'see -dar',
'-ie-' : 'USAN not to use',
'-ifen' : 'antiestrogens of the clomifene and tamoxifen groups',
'-ifene' : 'antiestrogens of the clomifene and tamoxifen groups',
'-igetide' : 'peptides and glycopeptides',
'-ii-' : 'USAN not to use',
'-ilide' : 'class iii antiarrhythmic agents',
'-imepodib' : 'inosine monophosphate dehydrogenase inhibitors',
'-imex-' : 'immunostimulants',
'-imibe-' : 'antihyperlipidaemics, acyl coa: cholesterol acyltransferase acat inhibitors',
'-imidar' : 'see dar',
'-imod' : 'immunomodulators',
'-imus' : 'immunosuppressives',
'-ine' : 'alkaloids and organic bases',
'-inostat' : 'inhibitors of histone deacetylase',
'-io-' : 'iodine-containing compounds other than contrast media',
'-iodarone' : 'indicates high iodine content',
'-iphene' : 'see -ifene',
'-irudin' : 'anticoagulants hirudin type',
'-isant' : 'histamine h3 receptor antagonists',
'-isomide' : 'antiarrhythmics disopyramide derivatives',
'-iu-' : 'USAN not to use',
'-ium' : 'quaternary ammonium derivatives',
'-iv' : 'intravenous; not necessarily prohibitive, but definitely causes hesitation',
'-ivon' : 'von willebrand factor inhibitors',
'-ixafor' : 'cxcr4 antagonists',
'-izine' : 'diphenylmethyl piperazine derivatives',
'-j-' : 'USAN not to use',
'-k-' : 'USAN not to use',
'-kacin' : 'antibiotics obtained from streptomyces kanamyceticus related to kanamycin',
'-kalant' : 'potassium channel antagonists',
'-kalim' : 'potassium channel agonists',
'-kalner' : 'opener of large conductance calcium-activated maxi-k k+ channels',
'-kef-' : 'enkephalin agonists various indications',
'-ki' : 'target: interleukin',
'-kin-' : 'interleukins as target',
'-kinra' : 'interleukin receptor antagonists',
'-kiren' : 'renin inhibitors',
'-laner' : 'antiparasitics isoxazoline compounds',
'-lanstat' : 'lanosterol 14a-demethylase inhibitors',
'-lazad' : 'lipid peroxidation inhibitors',
'-lazard' : 'lipid peroxidation inhibitors',
'-lefacept' : 'lymphocyte function-associated antigen 3',
'-leptin' : 'leptin derivatives',
'-leptine' : 'see leptin',
'-les-' : 'infix for inflammatory/infectious lesions',
'-leukin' : 'see -kin',
'-leuton' : '5-lipoxgenase inhibitors',
'-lev-' : 'USAN not to use; reserved for stereochemical compounds',
'-limumab' : 'see -mab',
'-lind' : 'pro-apoptotic cgmp phosphodiesterase inhibitors',
'-lintide' : 'amylin derivatives or mimics',
'-lipim' : 'lipoprotein lipase activators',
'-lisib' : 'phosphatidylinositol 3-kinase pi3k inhibitors',
'-listat' : 'gastrointestinal lipase inhibitors',
'-lizumab' : 'see -mab',
'-locib' : 'antineoplastics that inhibit the formation of 5-lo, ltb4, ltc4, and thromboxane b2 txb2; and activate ppar nuclear receptors',
'-lubant' : 'leukotriene receptor antagonists treatment of inflammatory skin disorders',
'-lukast' : 'leukotriene receptor antagonists',
'-lumab' : 'see -mab',
'-luren' : 'inducers of ribosomal readthrough of nonsense mutation mrna stop codons',
'-lutamide' : 'non-steroid antiandrogens',
'-lutril' : 'neutral endopeptidase inhibitors possessing additional endothelin converting enzyme inhibitory activity',
'-mab' : 'monoclonal antibodies',
'-manid' : 'mycolic acid inhibitors',
'-mantadine' : 'antivirals/antiparkinsonians',
'-mantine' : 'adamantane derivatives',
'-mantone' : 'adamantane derivatives',
'-mapimod' : 'mitogen-activated protein map kinase inhibitors',
'-maprazole' : 'acid pump inhibitors',
'-mastat' : 'matrix metalloprotease inhibitors',
'-meline' : 'cholinergic agonists arecoline derivatives used in treatment of alzheimers disease',
'-melteon' : 'selective melatonin receptor agonist',
'-mer' : 'polymers',
'-mesine' : 'sigma receptor ligands',
'-mestane' : 'antineoplastics aromatase inhibitors',
'-metacin' : 'anti-inflammatory agents indomethacin type',
'-metasone' : 'prednisone and prednisolone derivatives',
'-methasone' : 'prednisone and prednisolone derivatives',
'-micin' : 'antibiotics micromonospora strains',
'-mifene' : 'antiestrogens, clomifene and tamoxifen derivatives',
'-milast' : 'type iv phosphodiesterase inhibitors',
'-monam' : 'monobactam antibiotics',
'-morelin' : 'see -relin',
'-moren' : 'non-peptidic growth hormone secretagogues',
'-mostat' : 'enzyme inhibitors; proteolytic enzyme inhibitors',
'-mostim' : 'macrophage colony-stimulating factors m-csf',
'-motine' : 'antivirals quinoline derivatives',
'-moxin' : 'monoamine oxidase inhibitors hydrazine derivatives',
'-mulin' : 'antibacterials, pleuromulin derivatives',
'-multin' : 'mucosal tolerance inductors',
'-murtide' : 'peptides with muranic acid present',
'-mustine' : 'antineoplastics chloroethylamine derivatives',
'-mycin' : 'antibiotics streptomyces strains',
'-nab-' : 'cannabinol derivatives',
'-nabant' : 'cb cannabinoid receptor antagonists',
'-nacept' : 'interleukins',
'-nakalant' : 'mixed sodium/potassium channel blockers',
'-nakin' : 'see -kin',
'-nakinra' : 'interleukin-1 il-1 receptor antagonists',
'-nal-' : 'narcotic agonists/antagonists normorphine type',
'-napanor' : 'sodium-hydrogen antiporter also called sodium-proton exchanger inhibitors',
'-napant' : 'inhibitor of apoptosis protein iap inhibitors',
'-naritide' : 'peptides and glycopeptides',
'-navir' : 'see vir-',
'-ne-' : 'neurologic indications replaces -neu-',
'-nepag' : 'reduce conflicts with stems beginning with ne-, harmonize with inn experts, better reflect action at ep2 receptor',
'-neperit' : 'neuropeptide y5',
'-ner-' : 'neurologic indications replaces -neu-',
'-nercept' : 'see -cept',
'-nermin' : 'see -ermin',
'-nertant' : 'neurotensin receptor antagonists',
'-nesib' : 'kinesin inhibitors',
'-netant' : 'see -tant',
'-netide' : 'neurologic indications',
'-neurin' : 'neurotensin receptor antagonists; neurotropins',
'-ni-' : 'nicotine acid or nicotinoyl alcohol derivatives',
'-nicate' : 'antihypercholesterolaemic and/or vasodilating nicotinic acid esters',
'-nicline' : 'nicotinic acetylcholine receptor partial agonists/agonists',
'-nidap' : 'nonsteroidal anti-inflammatory agents tenidap type',
'-nidazole' : 'antiprotozoal substances metronidazole type',
'-nidine' : 'antihypertensives, clonidine derivatives',
'-nil' : 'benzodiazepine receptor antagonists/agonists',
'-nixin' : 'anti-inflammatory agents anilinonicotinic acid derivatives',
'-nonacog' : 'see -cog',
'-nonakin' : 'see -kin',
'-oa-' : 'USAN not to use',
'-octacog' : 'see -cog',
'-octadekin' : 'interleukin type substances',
'-octakin' : 'see -kin',
'-octocog' : 'blood coagulation factor viii',
'-oe-' : 'USAN not to use',
'-oi-' : 'USAN not to use',
'-ol' : 'for alcohols and phenols',
'-olol' : 'beta-blockers propranolol type',
'-olone' : 'steroids not prednisolone derivatives',
'-omab' : 'see -mab',
'-onakin' : 'interleukin-1a analogues and derivatives',
'-one' : 'ketones',
'-onide' : 'topical steroids acetal derivatives',
'-onidine' : 'antihypertensives, clonidine derivatives',
'-onium' : 'quaternary ammonium derivatives',
'-oo-' : 'USAN not to use',
'-opamine' : 'dopaminergic agents dopamine derivatives used as cardiac stimulant/antihypertensives/diuretics',
'-opilone' : 'epothilones',
'-opran' : 'opioid receptor antagonists',
'-orex' : 'anorexiants',
'-orexant' : 'see -orex',
'-orph-' : 'narcotic antagonists / agonists, morphinan derivates',
'-orphan-' : 'narcotic antagonists / agonists, morphinan derivates',
'-os-' : 'bone',
'-osuran' : 'urotensin receptor antagonists',
'-otermin' : 'bone morphogenetic proteins',
'-otilate' : 'hepatoprotectants, di-isopropyl-1,3-dithiol-malonate derivatives',
'-ou-' : 'USAN not to use',
'-ox' : 'antacids, aluminium derivatives',
'-oxacin' : 'antibacterials quinolone derivatives',
'-oxan' : 'alpha-adrenoceptor antagonists benzodioxane derivatives',
'-oxane' : 'benzodioxane derivatives',
'-oxanide' : 'antiparasitics salicylanilide derivatives',
'-oxef' : 'antibiotics oxacefalosporanic acid derivatives',
'-oxepin' : 'tricyclic compounds',
'-oxetine' : 'antidepressants fluoxetine type',
'-oxicam' : 'anti-inflammatory, isoxicam derivatives',
'-oxifene' : 'antiestrogens, clomifene and tamoxifen derivatives',
'-oxin' : 'fluoroquinolone derivatives, nonantibacterial indications e.g., antineoplastic antibiotics',
'-oxopine' : 'tricyclic compounds',
'-pab' : 'antibody mixtures/polyclonal antibodies, used instead of -mab',
'-pafant' : 'platelet-activating factor antagonists',
'-pamide' : 'diuretics sulfamoylbenzoic acid derivatives',
'-pamil' : 'coronary vasodilators verapamil type',
'-pamine' : 'dopaminergics butopamine type',
'-panel' : 'ampa receptor antagonists',
'-pansel' : 'p-selectin antagonists inhibiting all selectin types',
'-parantag' : 'antagonists of heparin and/or low molecular weight  heparins',
'-paratide' : 'see -tide',
'-parcil' : 'antithrombotics',
'-parcin' : 'glycopeptide antibiotics',
'-parib' : 'poly-adp-ribose polymerase inhibitors',
'-parin' : 'heparin derivatives and low molecular weight or depolymerized heparins',
'-parinux' : 'antithrombotyic indirect selective synthetic factor xa inhibitors',
'-paroid' : 'antithrombotics heparinoid type',
'-patril' : 'ace angiotensin-1 converting enzyme and nep neutral endopeptidase inhibitors',
'-patrilat' : 'ace angiotensin-1 converting enzyme and nep neutral endopeptidase inhibitors',
'-paxar' : 'par1 antagonists',
'-peg-' : 'pegylated compounds, covalent attachment of macrogol polyethylene glycol polymer',
'-pendyl' : 'vasodilators',
'-penem' : 'antibacterial antibiotics, carbapenem derivatives',
'-penkin' : 'see -kin',
'-peridol' : 'antipsychotics haloperidol type',
'-peridone' : 'antipsychotics risperidone type',
'-perit' : 'neuropeptide y receptor modulators',
'-perone' : 'antianxiety agents/neuroleptics 4-fluoro-4-piperidinobutyrophenone',
'-pertin' : 'glycine transporter/reuptake inhibitors',
'-pezil' : 'acetylcholinesterase inhibitors used in the treatment of alzheimers disease',
'-ph-' : 'USAN not to use',
'-pidem' : 'hypnotics/sedatives zolpidem type',
'-pin' : 'tricyclic compounds',
'-pine' : 'tricyclic compounds',
'-piprant' : 'prostaglandin receptor antagonists, non prostinoid structure',
'-piprazole' : 'psychotropics, phenylpiperazine derivatives',
'-pirdine' : 'cognition enhancers',
'-piro-' : 'USAN not to use; chemical connotations',
'-pirone' : 'anxiolytics, buspirone derivatives',
'-pirox' : 'antimycotics pyridone derivatives',
'-pitant' : 'see -tant',
'-plact' : 'platelet factor 4 analogs and derivatives',
'-pladib' : 'phospholipase a2 inhibitors',
'-planin' : 'antibacterials actinoplanes strains',
'-plase' : 'enzymes',
'-plasinin' : 'inhibitors of plasminogen activator inhibitors - type 1',
'-plasmid' : 'gene therapy products',
'-plasmin' : 'plasmin proteins and derivatives',
'-plasninin' : 'inhibitors of plasminogen activator inhibitors - type 1',
'-platin' : 'antineoplastics platinum derivatives',
'-plermin' : 'see -ermin',
'-plestim' : 'see -stim',
'-plon' : 'non-benzodiazepine anxiolytics, sedatives, hypnotics',
'-poetin' : 'erythropoietins',
'-por' : 'no definition',
'-porfin' : 'benzoporphyrin derivatives temoporfin',
'-poride' : 'na/h antiport inhibitor',
'-potide' : 'peptides with prostate cancer indications',
'-pramine' : 'antidepressants imipramine type',
'-prazan' : 'acid pump inhibitors, not dependent on acid activation',
'-prazole' : 'antiulcer agents benzimidazole derivatives',
'-pred-' : 'prednisone and prednisolone derivatives',
'-prenaline' : 'bronchodilators, phenethylamine derivatives',
'-pressin' : 'vasoconstrictors vasopressin derivatives',
'-previr' : 'serine protease inhibitors',
'-pride' : 'sulpiride derivatives',
'-pril-' : 'antihypertensives ace inhibitors',
'-prilat' : 'antihypertensives ace inhibitors diacid analogs of the -pril entity',
'-prim' : 'antibacterials trimethoprim type',
'-prinim' : 'nootropic agents, purine derivatives',
'-pris-' : 'steroidal compounds acting on progesterone receptors',
'-prisnil' : 'selective progesterone receptor modulators sprm',
'-pristin' : 'antibacterials, pristinamycin derivatives',
'-pristone' : 'progesterone receptor antagonists',
'-profen' : 'anti-inflammatory/analgesic agents ibuprofen type',
'-proget' : 'nonsteroidal ligand for the progesterone receptor',
'-prost-' : 'prostaglandins',
'-prostil' : 'prostaglandins, anti-ulcer',
'-protafib' : 'protein tyrosine phosphatase 1b inhibitors',
'-pultide' : 'see -tide',
'-punil' : 'mitochondrial benzodiazepine receptor mbr selective, partial, or inverse agonists purine derivatives',
'-quantel' : '2-deoxoparaherquamide a derivatives',
'-queside' : 'cholesterol sequestrants glycosides',
'-quidar' : 'quinoline derivatives',
'-quiline' : 'antibiotics, diarylquinoline structure',
'-quin' : 'quinoline derivatives',
'-quine' : 'quinoline derivatives',
'-quinil' : 'benzodiazepine receptor agonists, also partial or inverse quinoline derivatives',
'-quistat' : 'squalene synthase inhibitors',
'-rac-' : 'USAN not to use; reserved for stereochemical compounds',
'-racetam' : 'nootropes piracetam type',
'-racil' : 'uracil type antineoplastics',
'-rafenib' : 'raf kinase serine/threonine kinase inhibitors',
'-relin' : 'prehormones or hormone-release stimulating peptides',
'-relix' : 'hormone-release inhibiting peptides',
'-renone' : 'aldosterone antagonists spironolactone type',
'-restat-' : 'aldose-reductase inhibitors',
'-retin-' : 'retinol derivatives',
'-rev' : 'therapeutic virus',
'-rian' : 'ryanodine receptor modulators',
'-ribine' : 'ribofuranil derivatives pyrazofurin type',
'-rinone' : 'cardiotonics amrinone type',
'-ritide' : 'see -tide',
'-rixin' : 'chemokine c-x-c motif receptor 2 cxcr2 modulators',
'-rizine' : 'see -izine',
'-rocin' : 't-rna synthetase inhibitors',
'-rolimus' : 'immunosuppressant, rapamycin derivatives',
'-rozole' : 'aromatase inhibitors imidazole/triazole derivatives',
'-rsen' : 'antisense oligonucleotides',
'-rubicin' : 'antineoplastic antibiotics daunorubicin type',
'-sal-' : 'anti-inflammatory agents salicylic acid derivatives',
'-sarm' : 'selective androgen receptor modulator non-steroidal',
'-sartan' : 'angiotensin ii receptor antagonists',
'-semide' : 'diuretics furosemide type',
'-sermin' : 'see -ermin',
'-serod' : 'serotonin receptor antagonists and partial agonists',
'-serpine' : 'rauwolfia alkaloid derivatives',
'-sertib' : 'serine/threonine kinase inhibitors',
'-setrag' : 'serotonin 5-ht receptor agonists, not principally 5-ht2',
'-setron' : 'serotonin 5-ht3 antagonists',
'-siban' : 'oxytocin antagonists',
'-sidomine' : 'antianginals sydnone derivatives',
'-sidone' : 'antipsychotic with binding activity on serotonin 5ht2a and dopamine d2 receptors',
'-siranib' : 'sirna',
'-sonan' : '5-ht1b receptor antagonists',
'-sopine' : 'tricyclic compounds',
'-spirone' : 'anxiolytics buspirone type see -dar',
'-spo-' : 'ciclosporin d derivatives',
'-spodar' : 'ciclosporin d derivatives',
'-sporin' : 'immunosuppressants cyclosporine type',
'-sporivir' : 'see -vir',
'-stat-' : 'tryptophan hydroxylase inhibitors',
'-statin' : 'see -stat',
'-steine' : 'mucolytics, other than bromhexine derivatives',
'-ster-' : 'steroids androgens, anabolics',
'-steride' : 'testosterone reductase inhibitors',
'-stigmine' : 'cholinesterase inhibitors physostigmine type',
'-stim' : 'colony-stimulating factors',
'-stinel' : 'n-methyl-d-asprate nmda receptor antagonist, glycine recognition site',
'-sulam' : 'antineoplastics, apoptosis inducing sulfonamide',
'-sulfan' : 'antineoplastics, alkylating agents methanesulfonate derivatives',
'-sulind' : 'antineoplastics, sulindac metabolites',
'-tacept-' : 't-cells',
'-tadine' : 'loratadine derivatives',
'-tansine' : 'maytansinoid derivatives',
'-tant' : 'tachykinin neurokinin receptor antagonists',
'-tapide' : 'microsomal triglyceride transfer protein mtp inhibitors',
'-taxel' : 'antineoplastics, taxane derivatives',
'-tecan' : 'antineoplastics camptothecine derivatives',
'-tecarin' : 'antineoplastics rebeccamycin derivatives',
'-tegr-' : 'integrin antagonists',
'-tegrast' : 'see ast',
'-tegravir' : 'integrase inhibitors',
'-telstat' : 'telomerase inhibitors',
'-tepa' : 'antineoplastics thiotepa derivatives',
'-tepine' : 'tricyclic compounds',
'-teplase' : 'tissue-type plasminogen activators',
'-tercept' : 'transforming growth factor',
'-termin' : 'see -ermin',
'-terol' : 'bronchodilators phenethylamine derivatives',
'-terone' : 'antiandrogens',
'-tesind' : 'thymidilate synthetase inhibitors benzindole derivatives',
'-texafin' : 'texaphryn derivatives',
'-th-' : 'USAN not to use',
'-thiazide' : 'diuretics thiazide derivatives',
'-thiouracil' : 'uracil derivatives used as thyroid antagonists',
'-tiapine' : 'antipsychotics dibenzothiazepine derivatives',
'-tiazem' : 'calcium channel blockers diltiazem type',
'-tibant' : 'antiasthmatics bradykinin antagonists',
'-tide' : 'peptides',
'-tidine' : 'h2-receptor antagonists cimetidine type',
'-tilide' : 'class iii antiarrhythmics, sematilide derivatives',
'-tiline' : 'antidepressants, dibenzo [a,d] cycloheptane or cyclopheptene derivatives',
'-tinib' : 'tyrosine kinase inhibitors',
'-tiostat' : 'glutathione -s- transferase inhibitors',
'-tioxetine' : 'see -oxetine',
'-tirelin' : 'thyrotropin releasing hormone analogues',
'-tirimod' : 'napthyridine analogs',
'-tirome' : 'antihyperlipidemic, thyromimetic derivatives',
'-tizide' : 'diuretics, chlorothiazide derivatives',
'-tocin' : 'oxytocin derivatives',
'-toclax' : 'bcl-2 b-cell lymphoma 2 inhibitors',
'-toin' : 'antiepileptics hydantoin derivatives',
'-tolimod' : 'see -imod',
'-toran' : 'tlr4 receptor antagonists',
'-tox-' : 'toxins',
'-toxa-' : 'toxins',
'-trakin' : 'interleukin-4 analogues and derivatives',
'-trakinra' : 'interleukin receptor antagonists',
'-traline' : 'selective serotonin reuptake inhibitors ssri',
'-traposin' : 'ap2 inhibitors',
'-tredekin' : 'interleukin type substances',
'-trexate' : 'antimetabolites folic acid derivatives',
'-trexed' : 'antineoplastic thymidylate synthetase inhibitors',
'-tricin' : 'antibiotics polyene derivatives',
'-tril' : 'endopeptidase inhibitors',
'-trilat' : 'endopeptidase inhibitors',
'-triptan' : 'antimigraine agents 5-ht1 receptor agonists; sumatriptan derivatives',
'-triptyline' : 'antidepressants dibenzo[a,d]cycloheptane derivatives',
'-tristat' : 'tryptophan hydroxylase inhibitors',
'-troban' : 'antithrombotics thromboxane a2 receptor antagonists',
'-trodast' : 'thromboxane a2 receptor antagonists',
'-troline' : 'antipsychotics dopamine d2 antagonists',
'-trombopag' : 'thrombopoetin agonists',
'-trop-' : 'atropine derivatives',
'-tt-' : 'USAN not to use',
'-tucirev' : 'tumoricidal',
'-tumumab' : 'see -mab',
'-ua-' : 'USAN not to use',
'-uclin' : 'mucosal tolerance inhibitors',
'-ue-' : 'USAN not to use',
'-ui-' : 'USAN not to use',
'-umab' : 'see -mab',
'-unistat' : 'see -stat',
'-uo-' : 'USAN not to use',
'-uplase' : 'urokinase-type plasminogen activators',
'-uracil' : 'uracil derivatives used as thyroid antagonists and as antineoplastics',
'-urad' : 'urate transporter e.g., urate anion exchanger 1 urat1 inhibitors',
'-uramidine' : 'pentamidine derivatives/analogues',
'-urestat' : 'urease inhibitor',
'-uridine' : 'antivirals; antineoplastics uridine derivatives',
'-uu-' : 'USAN not to use',
'-vaptan' : 'vasopressin receptor antagonists',
'-vastatin' : 'see -stat',
'-vatrep' : 'vanilloid 1 receptor antagonists',
'-vec' : 'gene therapy products',
'-verine' : 'spasmolytic agents papaverine type',
'-vin-' : 'vinca alkaloids',
'-vir-' : 'antiviral substances undefined group',
'-vircept' : 'see -cept',
'-virdine' : 'see vir',
'-virenz' : 'antivirals non-nucleoside reverse transcriptase inhibitors; benzoxazinone derivatives',
'-virimat' : 'antiviral, disrupts viral maturation',
'-virine' : 'non-nucleoside reverse transcriptase inhibitors, not benzoxazinone derivatives',
'-viroc' : 'ccr5 antagonists',
'-virsen' : 'antivirals antisense',
'-vos' : 'insecticides, anthelminthics, pesticides etc., phosphorus derivatives',
'-vudine' : 'antineoplastics; antivirals zidovudine group exception: edoxudine',
'-w-' : 'USAN not to use',
'-xaban' : 'antithrombotic: blood coagulation factor xa inhibitors',
'-xanox' : 'antiallergic respiratory tract drugs xanoxic acid derivatives',
'-xantrone' : 'antineoplastics, mitoxantrone derivatives aza-anthracenedione class of antitumor agents',
'-ximab' : 'see -mab',
'-xizu-' : 'combination of humanized and chimeric chains',
'-xostat' : 'xanthine oxydase and xanthine urease inhibitor',
'-y-' : 'USAN not to use',
'-yzine' : 'diphenylmethyl piperazine derivatives',
'-zafone' : 'alozafone derivatives',
'-zepine' : 'see -pine',
'-zolamide' : 'carbonic anhydrase inhibitors',
'-zolast' : 'benzoxazole derivatives',
'-zolid' : 'oxazolidinone antibacterials',
'-zomib' : 'proteozome inhibitors',
'-zone' : 'see -buzone',
'-zotan' : '5-ht1a receptor agonists/antagonists acting primarily as neuroprotectors',
'-zotide' : 'zonulin antagonists',
'-zumab' : 'see -mab',
'al-' : 'USAN not to use; chemical connotations',
'arte-' : 'antimalarials artemisin derivatives',
'ba-' : 'USAN not to use; suggests chemical compound',
'bi-' : 'USAN not to use; numerical prefix',
'ca-' : 'USAN not to use; suggests chemical compound',
'cef-' : 'cephalosporins',
'cell-' : 'cellulose derivatives / cellulose ester derivatives for substances containinig acidic redidues',
'cent-' : 'USAN not to use; numerical prefix',
'deca-' : 'USAN not to use; numerical prefix',
'deci-' : 'USAN not to use; numerical prefix',
'di-' : 'USAN not to use; numerical prefix',
'dol-' : 'from "dolar" meaning "pain" in latin loose avoid',
'duo-' : 'USAN not to use; numerical prefix',
'dur-' : 'USAN not to use; claim',
'efex-' : 'USAN not to use; claim',
'es-' : 'USAN not to use; reserved for stereochemical compounds',
'fort-' : 'USAN not to use; claim',
'gado-' : 'gadolinium derivatives principally for diagnostic use',
'gly-' : 'antihyperglycemics',
'guan-' : 'antihypertensives guanidine derivatives',
'hept-' : 'USAN not to use; numerical prefix',
'iod-' : 'iodine-containing compounds other than contrast media',
'iv-' : 'intravenous; not necessarily prohibitive, but definitely causes hesitation',
'li-' : 'USAN not to use; chemical connotations',
'me-' : 'USAN not to use',
'mill-' : 'USAN not to use; numerical prefix',
'mito-' : 'antineoplastics, nucleotoxic agents',
'mono-' : 'USAN not to use; numerical prefix',
'nic-' : 'nicotine acid or nicotinoyl alcohol derivatives',
'nico-' : 'nicotine acid or nicotinoyl alcohol derivatives',
'nifur-' : '5-nitrofuran derivatives',
'nit-' : 'no2 - derivatives',
'nitr-' : 'no2 - derivatives',
'nitro-' : 'no2 - derivatives',
'oct-' : 'USAN not to use; numerical prefix',
'pegol-' : 'see peg',
'pent-' : 'USAN not to use; numerical prefix',
'perfl-' : 'perfluorinated compounds used as blood substitutes and/or diagnostic agents',
'perflu-' : 'blood substitutes and/or diagnostics perfluorochemicals',
'rifa-' : 'antibiotics rifamycin derivatives',
'semi-' : 'USAN not to use; numerical prefix',
'sexa-' : 'USAN not to use; numerical prefix',
'som-' : 'growth hormone derivatives',
'stan-' : 'USAN not to use; suggests chemical compound',
'str-' : 'USAN not to use',
'sulfa-' : 'antimicrobials sulfonamides derivatives',
'tetr-' : 'USAN not to use; numerical prefix',
'tri-' : 'USAN not to use; numerical prefix',
'uni-' : 'USAN not to use; numerical prefix',
'x-' : 'USAN not to use',
'z-' : 'USAN not to use'
}

STEMS["Prefix"] = [
'al', 'arte', 'ba', 'bi', 'ca', 'cef', 'cell', 'cent', 'deca', 'deci', 'di', \
'dol', 'duo', 'dur', 'efex', 'es', 'fort', 'gado', 'gly', 'guan', 'hept', \
'iod', 'iv', 'li', 'me', 'mill', 'mito', 'mono', 'nic', 'nico', 'nifur', \
'nit', 'nitr', 'nitro', 'oct', 'pegol', 'pent', 'perfl', 'perflu', 'rifa', \
'semi', 'sexa', 'som', 'stan', 'str', 'sulfa', 'tetr', 'tri', 'uni', 'x', 'z'
]

STEMS["Infix"] = [
'aa', 'acid', 'adol', 'ae', 'ai', 'aj', 'aldol', 'ampa', 'andr', 'ao', 'ar', \
'aril', 'arot', 'au', 'axo', 'barb', 'ben', 'bol', 'bu', 'cain', 'calci', \
'cat', 'cel', 'ch', 'co', 'cort', 'cri', 'dd', 'dex', 'dil', 'ea', 'ee', 'ei', \
'eo', 'erg', 'estr', 'eu', 'fen', 'fexor', 'fiba', 'flu', 'fo', 'fos', 'gab', \
'gest', 'gestr', 'gli', 'grel', 'h', 'ia', 'ie', 'ii', 'imex', 'imibe', 'io', \
'iu', 'j', 'k', 'kef', 'kin', 'les', 'lev', 'nab', 'nal', 'ne', 'ner', 'ni', \
'oa', 'oe', 'oi', 'oo', 'orph', 'orphan', 'os', 'ou', 'peg', 'ph', 'piro', \
'pred', 'pril', 'pris', 'prost', 'rac', 'restat', 'retin', 'sal', 'spo', \
'stat', 'ster', 'tacept', 'tegr', 'th', 'tox', 'toxa', 'trop', 'tt', 'ua', \
'ue', 'ui', 'uo', 'uu', 'vin', 'vir', 'w', 'xizu', 'y'
]

STEMS["Suffix"] = [
'abine', 'ac', 'acetam', 'actide', 'adom', 'adox', 'afenone', 'afil', 'al', \
'aldrate', 'algron', 'alol', 'alox', 'amidine', 'amidis', 'amivir', 'amostat', \
'ampanel', 'ampator', 'anib', 'anide', 'anserin', 'antel', 'antrone', 'apine', \
'apsel', 'arabine', 'arit', 'arol', 'arone', 'arotene', 'arsin', 'ase', 'ast', \
'asteride', 'astine', 'asvir', 'atadine', 'ate', 'axine', 'axomab', 'azam', \
'azenil', 'azepam', 'azepide', 'azocine', 'azolam', 'azoline', 'azone', \
'azosin', 'bacept', 'bactam', 'bamate', 'basib', 'begron', 'benakin', \
'bendan', 'bendazole', 'bercept', 'berel', 'bermin', 'bersat', 'betasol', \
'betin', 'bove', 'bradine', 'brate', 'brutinib', 'bufen', 'bulin', 'butan', \
'butazone', 'buvir', 'buzone', 'caftor', 'caine', 'calaret', 'calcet', \
'caleret', 'camra', 'camsule', 'capoc', 'capone', 'carbef', 'carnil', \
'casan', 'caserin', 'castat', 'catib', 'cavir', 'cellose', 'cept', 'cerfont', \
'cet', 'cetrapib', 'cic', 'ciclib', 'ciclovir', 'cidib', 'cidin', 'ciguat', \
'cillide', 'cillin', 'cillinam', 'cilpine', 'cirnon', 'cisteine', 'citabine', \
'citinib', 'cizumab', 'clidine', 'clidinium', 'clomol', 'clone', 'closporin', \
'clostox', 'cocept', 'codar', 'cog', 'cogin', 'conazole', 'corat', 'coxib', \
'cridar', 'crinat', 'crine', 'criviroc', 'cromil', 'curium', 'curonium', \
'cycline', 'cyclovir', 'dan', 'dapsone', 'dar', 'decakin', 'degib', 'denant', \
'denoson', 'depsin', 'dermin', 'dilol', 'dipine', 'dismase', 'distim', 'ditan', \
'ditraz', 'dodekin', 'domide', 'dopa', 'dopidine', 'dore', 'dotin', 'dotril', \
'dox', 'dralazine', 'drimer', 'drine', 'dronate', 'dronic', 'dutant', 'dyl', \
'ectedin', 'ectin', 'elestat', 'elvakin', 'elvekin', 'emcinal', 'enicokin', \
'entan', 'epag', 'eptacog', 'eptakin', 'eridine', 'ermin', 'espib', 'estrant', \
'etanide', 'ethidine', 'exakin', 'exine', 'ezolid', 'facept', 'farcept', \
'farin', 'farnib', 'faxine', 'fenacin', 'fenamate', 'fenamic', 'fenin', \
'fenine', 'fensine', 'fentanil', 'fentrine', 'fermin', 'fetamin', 'fetamine', \
'fexorate', 'fiban', 'fibatide', 'fibrate', 'fibric acid', 'filcon', \
'filermin', 'fingol', 'flapon', 'flurane', 'focon', 'folastat', 'formin', \
'fosfamide', 'fovir', 'fradil', 'frine', 'fulven', 'fungin', 'fylline', \
'gacestat', 'ganan', 'gapil', 'gaptide', 'gatran', 'gene', 'gepant', 'giline', \
'gillin', 'gliatin', 'gliflozin', 'glinide', 'gliptin', 'glitazar', \
'glitazone', 'glumide', 'glurant', 'glustat', 'glutide', 'golide', 'golix', \
'gosivir', 'gramostim', 'grastim', 'ibat', 'ibine', 'icam', 'icodar', 'ifen', \
'ifene', 'igetide', 'ilide', 'imepodib', 'imidar', 'imod', 'imus', 'ine', \
'inostat', 'iodarone', 'iphene', 'irudin', 'isant', 'isomide', 'ium', 'iv', \
'ivon', 'ixafor', 'izine', 'kacin', 'kalant', 'kalim', 'kalner', 'ki', \
'kinra', 'kiren', 'laner', 'lanstat', 'lazad', 'lazard', 'lefacept', 'leptin', \
'leptine', 'leukin', 'leuton', 'limumab', 'lind', 'lintide', 'lipim', 'lisib', \
'listat', 'lizumab', 'locib', 'lubant', 'lukast', 'lumab', 'luren', \
'lutamide', 'lutril', 'mab', 'manid', 'mantadine', 'mantine', 'mantone', \
'mapimod', 'maprazole', 'mastat', 'meline', 'melteon', 'mer', 'mesine', \
'mestane', 'metacin', 'metasone', 'methasone', 'micin', 'mifene', 'milast', \
'monam', 'morelin', 'moren', 'mostat', 'mostim', 'motine', 'moxin', 'mulin', \
'multin', 'murtide', 'mustine', 'mycin', 'nabant', 'nacept', 'nakalant', \
'nakin', 'nakinra', 'napanor', 'napant', 'naritide', 'navir', 'nepag', \
'neperit', 'nercept', 'nermin', 'nertant', 'nesib', 'netant', 'netide', \
'neurin', 'nicate', 'nicline', 'nidap', 'nidazole', 'nidine', 'nil', 'nixin', \
'nonacog', 'nonakin', 'octacog', 'octadekin', 'octakin', 'octocog', 'ol', \
'olol', 'olone', 'omab', 'onakin', 'one', 'onide', 'onidine', 'onium', \
'opamine', 'opilone', 'opran', 'orex', 'orexant', 'osuran', 'otermin', \
'otilate', 'ox', 'oxacin', 'oxan', 'oxane', 'oxanide', 'oxef', 'oxepin', \
'oxetine', 'oxicam', 'oxifene', 'oxin', 'oxopine', 'pab', 'pafant', 'pamide', \
'pamil', 'pamine', 'panel', 'pansel', 'parantag', 'paratide', 'parcil', \
'parcin', 'parib', 'parin', 'parinux', 'paroid', 'patril', 'patrilat', \
'paxar', 'pendyl', 'penem', 'penkin', 'peridol', 'peridone', 'perit', \
'perone', 'pertin', 'pezil', 'pidem', 'pin', 'pine', 'piprant', 'piprazole', \
'pirdine', 'pirone', 'pirox', 'pitant', 'plact', 'pladib', 'planin', 'plase', \
'plasinin', 'plasmid', 'plasmin', 'plasninin', 'platin', 'plermin', 'plestim', \
'plon', 'poetin', 'por', 'porfin', 'poride', 'potide', 'pramine', 'prazan', \
'prazole', 'prenaline', 'pressin', 'previr', 'pride', 'prilat', 'prim', \
'prinim', 'prisnil', 'pristin', 'pristone', 'profen', 'proget', 'prostil', \
'protafib', 'pultide', 'punil', 'quantel', 'queside', 'quidar', 'quiline', \
'quin', 'quine', 'quinil', 'quistat', 'racetam', 'racil', 'rafenib', 'relin', \
'relix', 'renone', 'rev', 'rian', 'ribine', 'rinone', 'ritide', 'rixin', \
'rizine', 'rocin', 'rolimus', 'rozole', 'rsen', 'rubicin', 'sarm', 'sartan', \
'semide', 'sermin', 'serod', 'serpine', 'sertib', 'setrag', 'setron', 'siban', \
'sidomine', 'sidone', 'siranib', 'sonan', 'sopine', 'spirone', 'spodar', \
'sporin', 'sporivir', 'statin', 'steine', 'steride', 'stigmine', 'stim', \
'stinel', 'sulam', 'sulfan', 'sulind', 'tadine', 'tansine', 'tant', 'tapide', \
'taxel', 'tecan', 'tecarin', 'tegrast', 'tegravir', 'telstat', 'tepa', \
'tepine', 'teplase', 'tercept', 'termin', 'terol', 'terone', 'tesind', \
'texafin', 'thiazide', 'thiouracil', 'tiapine', 'tiazem', 'tibant', 'tide', \
'tidine', 'tilide', 'tiline', 'tinib', 'tiostat', 'tioxetine', 'tirelin', \
'tirimod', 'tirome', 'tizide', 'tocin', 'toclax', 'toin', 'tolimod', 'toran', \
'trakin', 'trakinra', 'traline', 'traposin', 'tredekin', 'trexate', 'trexed', \
'tricin', 'tril', 'trilat', 'triptan', 'triptyline', 'tristat', 'troban', \
'trodast', 'troline', 'trombopag', 'tucirev', 'tumumab', 'uclin', 'umab', \
'unistat', 'uplase', 'uracil', 'urad', 'uramidine', 'urestat', 'uridine', \
'vaptan', 'vastatin', 'vatrep', 'vec', 'verine', 'vircept', 'virdine', \
'virenz', 'virimat', 'virine', 'viroc', 'virsen', 'vos', 'vudine', 'xaban', \
'xanox', 'xantrone', 'ximab', 'xostat', 'yzine', 'zafone', 'zepine', \
'zolamide', 'zolast', 'zolid', 'zomib', 'zone', 'zotan', 'zotide', 'zumab'
]
